name: Deann Experiments 

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # Pull the repository

    - name: Install 
      run: |
        docker build . -t deann-experiments
        
    - name: Run experiments on shuffle
      run: | 
        docker run -v "$(pwd)":/app/:rw -t deann-experiments python run_exp.py
        docker run -v "$(pwd)":/app/:rw -t deann-experiments python data_export.py -o res.csv
         docker run -v "$(pwd)":/app/:rw -t deann-experiments python additional/tabulate_results.py -i res.csv show-best


