name: Deann Experiments 

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # Pull the repository

    - name: Install 
      run: |
          pip3 install -r requirements.txt
          python3 install.py
        
        
    - name: Run experiments on shuttle
      run: | 
          python run_exp.py --algorithm hbe
          python run_exp.py --algorithm deann
          python run_exp.py --algorithm sklearn


