name: Deann Experiments 

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # Pull the repository

    - name: Install 
      run: |
        docker build . -t deann-experiments
        
    - name: Run experiments on shuffle
      run: | 
        docker -v "$(pwd)":/app/:rw -t deann-experiments python run_exp.py
